### ISSUE TITLE
Ability to scrap Jewelry in forge the same as Weapons and Armor

### ISSUE THREAD

**Issue by HiroRogue** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Samuel-IH** [comment]
Jewelry currently only requires one ingot and one gem. The items are generally scrapped for half of what was used to produce them, which would result in half an ingot and half a gem.

Going to close this for now, but it may be reopened later if we decide to use a random roll instead.

**Comment by Samuel-IH** [comment]
Reopening.
After looking at https://github.com/A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System/issues/17 I've decided we need this.

**Comment by HiroRogue** [comment]
Suggestion, as the Rings and Amulets scale up have then require more gems and ingots.

**Comment by HiroRogue** [comment]
Suggestion, as rings and amulets scale up have them require more gems and ingots to produce.

**Comment by BarchamMal** [comment]
> Suggestion, as rings and amulets scale up have them require more gems and ingots to produce.

This is not realistic at all. The only difficulty in making jewelry IRL is motor skills and wire hardness.
If higher tier metals are harder, this might use slightly more wire, but not more gems.

Just like if you fail to craft a piece of jewelry should _always_  get the gem back and _never_ get the metal back.
Because in jewelry crafting, you clip, bend, and flatten the wire, while all you do to the gem is fasten in place without damaging it.

**Comment by BarchamMal** [comment]
> Suggestion, as rings and amulets scale up have them require more gems and ingots to produce.

Also, no need to make jewelry harder to craft; the ingredients are harder to get.
