### ISSUE TITLE
No charcoal when lighting a tree on fire with GTS rubicite gloves

### ISSUE THREAD

**Issue by dpeart** [A-Dawn-of-Heroes-NWN-EE-PW/New-Crafting-System#34]
I've made charcoal by using flame weapon on an axe and chopping the tree.

My monk crafter doesn't have flame weapon so I used the GTS rubicite gloves to start the tree on fire, then switched to a hand axe to finish chopping it.

I didn't get any charcoal, just logs.

I then beat the tree to death with the gloves, and just got fewer logs, still no charcoal

**Comment by Samuel-IH** [comment]
In order to drop charcoal the tree has to take more than 50% of its total health in fire damage. I just tested it, it does work. The issue here is that it is a challenge to minimally damage a tree with monk APR.

If trying to set a tree on fire with gloves, i suggest you punch it and immediately back away. Try not to crit.

**Comment by dpeart** [comment]
so I can just let the fire do all the work.  I'll try that . . . yep, that works.
